package model.service;

import model.dao.EnrollmentDao;
import model.dao.RecitationDao;
import model.dao.TasmiSessionDao;
import model.dao.impl.EnrollmentDaoJdbc;
import model.dao.impl.RecitationDaoJdbc;
import model.dao.impl.TasmiSessionDaoJdbc;
import model.entity.Enrollment;
import model.entity.Recitation;
import model.entity.TasmiSession;
import model.service.quran.RecitationReferenceService;
import model.service.quran.TrustedReference;
import model.service.quran.TrustedReferenceResult;
import util.Db;
import util.RecitationMediaLoader;

import java.sql.Connection;
import java.util.Optional;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 * Server-side AI Learning Loop pipeline (Quranpedia → STT → deterministic comparison → OpenAI explanation).
 * Used for automatic post-submission analysis and instructor-initiated retries.
 */
public class RecitationAnalysisPipeline {
    private static final Logger LOGGER = Logger.getLogger(RecitationAnalysisPipeline.class.getName());

    private final RecitationDao recitationDao = new RecitationDaoJdbc();
    private final EnrollmentDao enrollmentDao = new EnrollmentDaoJdbc();
    private final TasmiSessionDao tasmiSessionDao = new TasmiSessionDaoJdbc();
    private final RecitationAiAnalysisService aiAnalysisService = new RecitationAiAnalysisService();
    private final RecitationAnalysisService analysisService = new RecitationAnalysisService();

    public void runForRecitation(long recitationId) {
        if (recitationId <= 0) {
            return;
        }
        RecitationAiAnalysisService.AnalysisResult result;
        try (Connection connection = Db.getConnection()) {
            Optional<Recitation> recitationOpt = recitationDao.findById(connection, recitationId);
            if (recitationOpt.isEmpty()) {
                LOGGER.warning("Auto analysis skipped: recitation not found id=" + recitationId);
                return;
            }
            Recitation recitation = recitationOpt.get();
            Optional<Enrollment> enrollmentOpt = enrollmentDao.findById(connection, recitation.getEnrollmentId());
            if (enrollmentOpt.isEmpty()) {
                persistSafeFailure(recitationId,
                        RecitationAiAnalysisService.AnalysisResult.failed("Enrollment not found for this recitation."));
                return;
            }
            TasmiSession session = tasmiSessionDao.findById(connection, enrollmentOpt.get().getSessionId()).orElse(null);
            if (!LearningLoopPublicationPolicy.hasStructuredSessionRange(session)) {
                persistSafeFailure(recitationId, RecitationAiAnalysisService.AnalysisResult.failed(
                        "Structured Qur'an passage (surah and ayah range) is required for AI Learning Loop analysis."));
                return;
            }

            Integer surahNumber = session.getSurahNumber();
            Integer ayahStart = session.getAyahStart();
            Integer ayahEnd = session.getAyahEnd();
            String expectedLabel = session.getQuranPortion();

            TrustedReferenceResult referenceResult = RecitationReferenceService.getInstance()
                    .fetch(surahNumber, ayahStart, ayahEnd);
            if (!referenceResult.isOk()) {
                LOGGER.log(Level.WARNING, "REFERENCE_UNAVAILABLE for recitation {0}: {1}",
                        new Object[]{recitationId, referenceResult.getReason()});
                persistSafeFailure(recitationId, aiAnalysisService.referenceUnavailable(
                        "The trusted Qur'an reference is unavailable, so the AI comparison was withheld. "
                                + "No Qur'an text was generated by AI."));
                return;
            }
            TrustedReference trustedReference = referenceResult.getReference();

            byte[] mediaBytes = RecitationMediaLoader.readBytes(recitation.getAudioFilePath());
            if (mediaBytes == null || mediaBytes.length == 0) {
                persistSafeFailure(recitationId, RecitationAiAnalysisService.AnalysisResult.cannotEvaluate(
                        "Recitation media is unavailable for AI analysis."));
                return;
            }
            String fileName = RecitationMediaLoader.fileName(recitation.getAudioFilePath(), recitationId);
            result = aiAnalysisService.analyze(trustedReference, expectedLabel, mediaBytes, fileName);
        } catch (Exception ex) {
            LOGGER.log(Level.SEVERE, "Auto analysis pipeline failed for recitation " + recitationId, ex);
            persistSafeFailure(recitationId,
                    RecitationAiAnalysisService.AnalysisResult.failed("Analysis could not be completed."));
            return;
        }

        try {
            analysisService.saveForRecitation(recitationId, result);
            LOGGER.info("Auto analysis persisted recitation_id=" + recitationId
                    + " status=" + (result.getStatus() == null ? "?" : result.getStatus().name()));
        } catch (Exception ex) {
            LOGGER.log(Level.SEVERE, "Failed to persist auto analysis for recitation " + recitationId, ex);
        }
    }

    private void persistSafeFailure(long recitationId, RecitationAiAnalysisService.AnalysisResult result) {
        try {
            analysisService.saveForRecitation(recitationId, result);
        } catch (Exception ex) {
            LOGGER.log(Level.SEVERE, "Failed to persist safe failure for recitation " + recitationId, ex);
        }
    }
}
